### ISSUE TITLE
Need tags for Carthage to work properly. 

### ISSUE THREAD

**Issue by bwhiteley** [johnpatrickmorgan/KeyboardLayoutGuide#4]
Currently to use KeyboardLayoutGuide with Carthage, you have to add this to your `Cartfile`:

    github "johnpatrickmorgan/KeyboardLayoutGuide" "master"

(Note the "master"). This is contrary to the README, and it is generally better to use a tag. However, the most recent tag doesn't include a shared scheme for Carthage to work. 

Here's what needs to happen: 
1. Tag LifecycleHooks (different repo) so that there is a tag with Carthage support. 
2. Edit the `Cartfile` and remove the "master" for LifecycleHooks. 
3. Run `carthage update --no-checkout` to update `Cartfile.resolved`
4. Commit the new `Cartfile` and `Cartfile.resolved`
5. Tag KeyboardLayoutGuide.

**Comment by johnpatrickmorgan** [comment]
Thanks for the detailed instructions. I believe the required changes have now been made. 👍
